os:
  - 'linux'
dist: trusty
language: node_js
node_js:
  - '10.15.0'
cache:
  directories:
    - ./node_modules

before_install:
  - npm install -g npm@6.10.3

install:
  - npm install

script:
  - npm run test
  - npm run lint